import { SupportLanguage } from '../types';

const en = {
  title: 'Sanskrit transcription',
  subtitle: 'Su-shrota v13b · on-device recognition',
  privacy: 'Audio stays in this browser. No login or API key needed. First use downloads a 179 MiB model from Hugging Face; cached when storage is available.',
  download: 'Download speech model',
  loading: 'Downloading model',
  compiling: 'Preparing recognition engine…',
  ready: 'Model ready · audio processed locally',
  record: 'Record Sanskrit',
  stop: 'Stop & transcribe',
  recording: 'Recording (15 seconds maximum)',
  transcribing: 'Transcribing on this device…',
  upload: 'Upload audio',
  sample: 'Try public sample',
  sampleReference: 'Public sample reference: परस्परानुकथनं',
  attribution: 'Sample: Prathosh A P / IISc, Su-shrota dataset (CC-BY-4.0). ASR by Prathosh A P; ONNX conversion by gnumanth.',
  transcript: 'Recognized Sanskrit · review and edit',
  resultNote: 'Recognition can make mistakes. This is a transcript, not a pronunciation grade.',
  recordingPlayback: 'Your recording · input replay (not model-generated speech)',
  samplePlayback: 'Public sample audio · input replay (not model-generated speech)',
  use: 'Use in tutor reply',
  useLocal: 'Use as local Sanskrit input',
  localNotice: 'Using the transcript only fills the local tutor input. Run locally sends the text to your paired companion, never the recording.',
  sendNotice: 'Using the transcript fills your reply. Only Send shares text with the tutor; audio is not sent.',
  cancel: 'Cancel',
  retry: 'Retry model download',
  modelError: 'Could not load the speech model. Check your connection and retry.',
  inferenceError: 'Recognition failed. Try a shorter, clearer recording.',
  cacheWarning: 'Browser storage is unavailable or full. Recognition can run, but the model may need to download again.',
  micError: 'Microphone unavailable. Allow microphone access on localhost/HTTPS, or upload an audio file.',
  audioError: 'Could not read this audio. Try a WAV, MP3, or a browser-supported recording.',
  durationError: 'Use an audio clip between 0.4 and 15 seconds (maximum file size: 10 MB).',
  silence: 'No clear speech detected. Speak closer to the microphone and try again.',
  secureError: 'Local recognition requires a modern browser on HTTPS or localhost.',
  time: 'Recognition time',
  seconds: 's',
  milliseconds: 'ms',
  tutorUnavailable: 'Transcription works without a server. AI tutor replies require a separately configured OpenAI API endpoint.',
};

export const speechCopy: Record<SupportLanguage, typeof en> = {
  en,
  hi: {
    title: 'संस्कृत लिप्यंतरण', subtitle: 'Su-shrota v13b · इसी उपकरण पर पहचान',
    privacy: 'ऑडियो इसी ब्राउज़र में रहता है। लॉगिन या API कुंजी नहीं चाहिए। पहली बार Hugging Face से 179 MiB मॉडल डाउनलोड होता है; जगह होने पर सुरक्षित रहता है।',
    download: 'वाणी मॉडल डाउनलोड करें', loading: 'मॉडल डाउनलोड हो रहा है', compiling: 'पहचान इंजन तैयार हो रहा है…',
    ready: 'मॉडल तैयार · ऑडियो का स्थानीय विश्लेषण', record: 'संस्कृत रिकॉर्ड करें', stop: 'रोकें और लिप्यंतरण करें',
    recording: 'रिकॉर्ड हो रहा है (अधिकतम 15 सेकंड)', transcribing: 'इसी उपकरण पर लिप्यंतरण…',
    upload: 'ऑडियो अपलोड करें', sample: 'सार्वजनिक नमूना आज़माएँ', sampleReference: 'नमूने का पाठ: परस्परानुकथनं',
    attribution: 'नमूना: Prathosh A P / IISc, Su-shrota डेटासेट (CC-BY-4.0)। ASR: Prathosh A P; ONNX: gnumanth।',
    transcript: 'पहचाना गया संस्कृत पाठ · जाँचें और सुधारें', resultNote: 'पहचान में त्रुटियाँ हो सकती हैं। यह लिप्यंतरण है, उच्चारण का अंक नहीं।',
    recordingPlayback: 'आपकी रिकॉर्डिंग · इनपुट फिर से चलाएँ (मॉडल की बनाई आवाज़ नहीं)',
    samplePlayback: 'सार्वजनिक नमूना ऑडियो · इनपुट फिर से चलाएँ (मॉडल की बनाई आवाज़ नहीं)',
    use: 'शिक्षक के उत्तर में उपयोग करें', sendNotice: 'पाठ आपके उत्तर में भरेगा। भेजने पर केवल पाठ शिक्षक को जाता है, ऑडियो नहीं।',
    useLocal: 'स्थानीय संस्कृत इनपुट में उपयोग करें', localNotice: 'यह केवल स्थानीय शिक्षक का इनपुट भरेगा। स्थानीय रूप से चलाने पर पाठ सहायक को जाएगा, रिकॉर्डिंग नहीं।',
    cancel: 'रद्द करें', retry: 'मॉडल डाउनलोड पुनः करें', modelError: 'वाणी मॉडल लोड नहीं हुआ। कनेक्शन जाँचकर पुनः प्रयास करें।',
    inferenceError: 'पहचान विफल हुई। छोटा और स्पष्ट रिकॉर्डिंग आज़माएँ।', cacheWarning: 'ब्राउज़र में जगह नहीं है। मॉडल फिर डाउनलोड करना पड़ सकता है।',
    micError: 'माइक्रोफ़ोन उपलब्ध नहीं। localhost/HTTPS पर अनुमति दें या ऑडियो फ़ाइल चुनें।',
    audioError: 'ऑडियो नहीं पढ़ सके। WAV, MP3 या समर्थित रिकॉर्डिंग आज़माएँ।', durationError: '0.4 से 15 सेकंड की क्लिप चुनें (अधिकतम 10 MB)।',
    silence: 'स्पष्ट वाणी नहीं मिली। माइक्रोफ़ोन के पास बोलकर पुनः प्रयास करें।', secureError: 'पहचान के लिए आधुनिक ब्राउज़र और HTTPS या localhost चाहिए।',
    time: 'पहचान का समय', seconds: 'सेकंड', milliseconds: 'मिलीसेकंड', tutorUnavailable: 'लिप्यंतरण बिना सर्वर चलता है। AI शिक्षक के लिए अलग OpenAI API विन्यास चाहिए।',
  },
  te: {
    useLocal: 'స్థానిక సంస్కృత ఇన్‌పుట్‌గా వాడండి',
    localNotice: 'ఇది స్థానిక గురువు ఇన్‌పుట్‌ను మాత్రమే నింపుతుంది. స్థానికంగా నడిపినప్పుడు పాఠం మీ సహాయకానికి వెళ్తుంది, రికార్డింగ్ కాదు.',
    title: 'సంస్కృత లిప్యంతరీకరణ', subtitle: 'Su-shrota v13b · ఈ పరికరంలోనే గుర్తింపు',
    privacy: 'ఆడియో ఈ బ్రౌజర్‌లోనే ఉంటుంది. లాగిన్ లేదా API కీ అవసరం లేదు. మొదట Hugging Face నుంచి 179 MiB మోడల్ దిగుమతి అవుతుంది; స్థలం ఉంటే నిల్వ ఉంటుంది.',
    download: 'వాణి మోడల్ దిగుమతి', loading: 'మోడల్ దిగుమతి అవుతోంది', compiling: 'గుర్తింపు ఇంజిన్ సిద్ధమవుతోంది…',
    ready: 'మోడల్ సిద్ధం · స్థానిక ఆడియో గుర్తింపు', record: 'సంస్కృతం రికార్డ్ చేయండి', stop: 'ఆపి లిప్యంతరీకరించండి',
    recording: 'రికార్డింగ్ (గరిష్ఠంగా 15 సెకన్లు)', transcribing: 'ఈ పరికరంలో లిప్యంతరీకరణ…',
    upload: 'ఆడియో ఎంచుకోండి', sample: 'పబ్లిక్ నమూనా ప్రయత్నించండి', sampleReference: 'నమూనా పాఠం: परस्परानुकथनं',
    attribution: 'నమూనా: Prathosh A P / IISc, Su-shrota డేటాసెట్ (CC-BY-4.0). ASR: Prathosh A P; ONNX: gnumanth.',
    transcript: 'గుర్తించిన సంస్కృతం · పరిశీలించి సవరించండి', resultNote: 'గుర్తింపులో తప్పులు ఉండవచ్చు. ఇది లిప్యంతరీకరణ, ఉచ్చారణ మార్కు కాదు.',
    recordingPlayback: 'మీ రికార్డింగ్ · ఇన్‌పుట్‌ను మళ్లీ వినండి (మోడల్ సృష్టించిన మాట కాదు)',
    samplePlayback: 'పబ్లిక్ నమూనా ఆడియో · ఇన్‌పుట్‌ను మళ్లీ వినండి (మోడల్ సృష్టించిన మాట కాదు)',
    use: 'గురువు సమాధానంలో వాడండి', sendNotice: 'పాఠం మీ సమాధానంలో చేరుతుంది. పంపినప్పుడు పాఠం మాత్రమే గురువుకు వెళ్తుంది; ఆడియో కాదు.',
    cancel: 'రద్దు', retry: 'మోడల్ దిగుమతి మళ్లీ ప్రయత్నించండి', modelError: 'వాణి మోడల్ రాలేదు. కనెక్షన్ చూసి మళ్లీ ప్రయత్నించండి.',
    inferenceError: 'గుర్తింపు విఫలమైంది. చిన్న, స్పష్టమైన రికార్డింగ్ ప్రయత్నించండి.', cacheWarning: 'బ్రౌజర్ నిల్వ అందుబాటులో లేదు. మోడల్ మళ్లీ దిగుమతి కావచ్చు.',
    micError: 'మైక్రోఫోన్ అందుబాటులో లేదు. localhost/HTTPS లో అనుమతించండి లేదా ఆడియో ఎంచుకోండి.',
    audioError: 'ఈ ఆడియో చదవలేకపోయాం. WAV, MP3 లేదా మద్దతున్న రికార్డింగ్ ప్రయత్నించండి.', durationError: '0.4 నుంచి 15 సెకన్ల క్లిప్ ఎంచుకోండి (గరిష్ఠంగా 10 MB).',
    silence: 'స్పష్టమైన మాట వినిపించలేదు. మైక్రోఫోన్ దగ్గర మాట్లాడి మళ్లీ ప్రయత్నించండి.', secureError: 'స్థానిక గుర్తింపుకు ఆధునిక బ్రౌజర్, HTTPS లేదా localhost అవసరం.',
    time: 'గుర్తింపు సమయం', seconds: 'సెకన్లు', milliseconds: 'మిల్లీసెకన్లు', tutorUnavailable: 'లిప్యంతరీకరణకు సర్వర్ అవసరం లేదు. AI గురువుకు వేరుగా OpenAI API అమరిక అవసరం.',
  },
};
