import { SupportLanguage } from '../types';
import { usingHostedTutor } from './api';

const en = {
  title: 'Local Sanskrit tutor',
  intro: 'Teach, converse, and explore word forms using a companion running on this computer. No account or cloud fallback.',
  pairing: 'Pair with your companion',
  setup: 'Start the Python companion, then run vakya-companion --show-token in your own terminal. Paste that token here. It stays in memory and is never included in share links.',
  token: 'Local pairing token',
  connect: 'Connect / refresh providers',
  disconnect: 'Disconnect',
  connected: 'Connected to this computer',
  connecting: 'Connecting…',
  source: 'Input language',
  teach: 'Teach',
  converse: 'Converse',
  analyze: 'Word analysis',
  placeholder: 'Enter a short sentence (up to 400 characters)…',
  submit: 'Run locally',
  working: 'Local model is working…',
  cancel: 'Cancel waiting',
  cancelNote: 'Waiting cancelled. An active model may finish its current inference before another request can run.',
  privacy: 'Only Run locally sends text to your paired loopback service. No text goes to OpenAI. Every recipient of this link needs their own companion.',
  machine_translation: 'Machine translation: review meaning and Sanskrit accuracy.',
  experimental_conversation: 'Experimental conversation: this model can confuse languages and invent teaching facts. Not verified Sanskrit instruction.',
  conversationNote: 'Conversation requires all translation models, local Qwen, and explicit experimental opt-in in the companion.',
  transliteration_only: 'Sanskrit input: normalized and transliterated, not translated or validated.',
  candidate_analysis: 'Candidate word analyses, not a grammar verdict. Missing candidates do not prove a mistake. Tags use the provider’s Sanskrit notation.',
  provider: 'Provider',
  ready: 'Installed',
  missing: 'Not installed',
  unavailable: 'This operation needs a provider that is not installed. Provision it in the companion, then refresh.',
  noCandidates: 'No candidates found',
  speechMissing: 'Local Sanskrit speech is not activated yet; no Hindi/browser voice is substituted.',
  native: 'Use Local Tutor in a desktop browser on the same computer as the companion. Phone-to-desktop pairing is not enabled.',
  unreachable: 'Cannot reach the companion. Start it on this computer and allow local-network access. If your browser blocks the public site, open the localhost app.',
  unauthorized: 'Pairing failed. Copy the current local token and reconnect.',
  forbidden_origin: 'The companion rejected this page origin. Use the approved localhost or Vākya Pages app.',
  provider_unavailable: 'The required local provider is not installed or configured.',
  busy: 'Another local inference is still running. Wait before retrying.',
  quota_exceeded: 'The daily request limit has been reached. Please try again tomorrow.',
  invalid_request: 'Check the input language and use a short, nonempty sentence.',
  invalid_output: 'The provider returned an incomplete or invalid result. Try again; no fallback was used.',
  inference_failed: 'Local inference failed. Check the companion installation and try again.',
  clear: 'Clear conversation',
};
export const localCopy: Record<SupportLanguage, typeof en> = {
  en,
  hi: {
    title: 'स्थानीय संस्कृत शिक्षक',
    intro: 'इसी कंप्यूटर पर चलने वाले सहायक से सीखें, बातचीत करें और शब्दरूप देखें। कोई खाता या क्लाउड विकल्प नहीं।',
    pairing: 'अपने स्थानीय सहायक से जुड़ें',
    setup: 'Python सहायक शुरू करें, फिर अपने टर्मिनल में vakya-companion --show-token चलाएँ। टोकन यहाँ डालें। यह केवल मेमोरी में रहता है, साझा लिंक में नहीं।',
    token: 'स्थानीय कनेक्शन टोकन', connect: 'जुड़ें / प्रदाता स्थिति देखें', disconnect: 'कनेक्शन हटाएँ',
    connected: 'इस कंप्यूटर से जुड़ा है', connecting: 'जुड़ रहा है…', source: 'इनपुट भाषा',
    teach: 'सीखें', converse: 'बातचीत', analyze: 'शब्द विश्लेषण',
    placeholder: 'एक छोटा वाक्य लिखें (अधिकतम 400 अक्षर)…', submit: 'स्थानीय रूप से चलाएँ',
    working: 'स्थानीय मॉडल काम कर रहा है…', cancel: 'प्रतीक्षा रद्द करें',
    cancelNote: 'प्रतीक्षा रद्द हुई। नया अनुरोध चलने से पहले वर्तमान मॉडल अपना काम पूरा कर सकता है।',
    privacy: 'स्थानीय रूप से चलाने पर ही पाठ आपके कंप्यूटर के सहायक को जाता है। OpenAI को नहीं। लिंक पाने वाले प्रत्येक व्यक्ति को अपना सहायक चाहिए।',
    machine_translation: 'मशीनी अनुवाद: अर्थ और संस्कृत की शुद्धता जाँचें।',
    experimental_conversation: 'प्रायोगिक बातचीत: मॉडल भाषाएँ मिला सकता है और गलत शिक्षण तथ्य बना सकता है। यह सत्यापित संस्कृत शिक्षा नहीं है।',
    conversationNote: 'बातचीत के लिए सभी अनुवाद मॉडल, स्थानीय Qwen और सहायक में स्पष्ट प्रायोगिक अनुमति चाहिए।',
    transliteration_only: 'संस्कृत इनपुट: केवल सामान्यीकरण और लिप्यंतरण, अनुवाद या सत्यापन नहीं।',
    candidate_analysis: 'संभावित शब्द विश्लेषण, व्याकरण का निर्णय नहीं। विश्लेषण न मिलने का अर्थ त्रुटि नहीं है। टैग प्रदाता की संस्कृत संज्ञाओं में हैं।',
    provider: 'प्रदाता', ready: 'स्थापित', missing: 'स्थापित नहीं',
    unavailable: 'इस कार्य का प्रदाता स्थापित नहीं है। सहायक में स्थापित करके स्थिति फिर देखें।',
    noCandidates: 'कोई संभावित विश्लेषण नहीं मिला',
    speechMissing: 'स्थानीय संस्कृत वाणी अभी सक्रिय नहीं है; हिन्दी या ब्राउज़र की आवाज़ नहीं लगाई जाएगी।',
    native: 'सहायक वाले कंप्यूटर के डेस्कटॉप ब्राउज़र में स्थानीय शिक्षक खोलें। फ़ोन से कंप्यूटर का कनेक्शन अभी उपलब्ध नहीं है।',
    unreachable: 'सहायक नहीं मिला। इसे इस कंप्यूटर पर शुरू करें और स्थानीय नेटवर्क की अनुमति दें। सार्वजनिक साइट अवरुद्ध हो तो localhost ऐप खोलें।',
    unauthorized: 'कनेक्शन असफल। वर्तमान स्थानीय टोकन डालकर फिर जुड़ें।',
    forbidden_origin: 'सहायक ने इस पृष्ठ का स्रोत अस्वीकार किया। अनुमत localhost या वाक्य Pages ऐप उपयोग करें।',
    provider_unavailable: 'ज़रूरी स्थानीय प्रदाता स्थापित या विन्यस्त नहीं है।',
    busy: 'एक स्थानीय अनुरोध अभी चल रहा है। फिर प्रयास करने से पहले प्रतीक्षा करें।',
    quota_exceeded: 'आज की अनुरोध सीमा पूरी हो गई है। कृपया कल फिर प्रयास करें।',
    invalid_request: 'इनपुट भाषा जाँचें और एक छोटा, खाली न होने वाला वाक्य लिखें।',
    invalid_output: 'प्रदाता ने अधूरा या अमान्य परिणाम दिया। फिर प्रयास करें; कोई वैकल्पिक सेवा नहीं लगाई गई।',
    inference_failed: 'स्थानीय विश्लेषण विफल हुआ। सहायक की स्थापना जाँचकर फिर प्रयास करें।',
    clear: 'बातचीत साफ़ करें',
  },
  te: {
    title: 'స్థానిక సంస్కృత గురువు',
    intro: 'ఈ కంప్యూటర్‌లో నడిచే సహాయకంతో నేర్చుకోండి, సంభాషించండి, పదరూపాలను పరిశీలించండి. ఖాతా లేదా క్లౌడ్ ప్రత్యామ్నాయం లేదు.',
    pairing: 'మీ స్థానిక సహాయకానికి కనెక్ట్ అవ్వండి',
    setup: 'Python సహాయకాన్ని ప్రారంభించి, మీ టెర్మినల్‌లో vakya-companion --show-token నడపండి. టోకెన్‌ను ఇక్కడ ఇవ్వండి. ఇది మెమరీలో మాత్రమే ఉంటుంది, షేర్ లింకుల్లో కాదు.',
    token: 'స్థానిక కనెక్షన్ టోకెన్', connect: 'కనెక్ట్ / ప్రొవైడర్ల స్థితి చూడండి', disconnect: 'డిస్‌కనెక్ట్',
    connected: 'ఈ కంప్యూటర్‌కు కనెక్ట్ అయింది', connecting: 'కనెక్ట్ అవుతోంది…', source: 'ఇన్‌పుట్ భాష',
    teach: 'నేర్చుకోండి', converse: 'సంభాషణ', analyze: 'పద విశ్లేషణ',
    placeholder: 'ఒక చిన్న వాక్యం ఇవ్వండి (గరిష్ఠంగా 400 అక్షరాలు)…', submit: 'స్థానికంగా నడపండి',
    working: 'స్థానిక మోడల్ పనిచేస్తోంది…', cancel: 'వేచి ఉండటం రద్దు',
    cancelNote: 'వేచి ఉండటం రద్దయింది. కొత్త అభ్యర్థనకు ముందు మోడల్ ప్రస్తుత పనిని పూర్తి చేయవచ్చు.',
    privacy: 'స్థానికంగా నడిపినప్పుడే పాఠం మీ కంప్యూటర్‌లోని సహాయకానికి వెళ్తుంది. OpenAIకి కాదు. లింక్ పొందిన ప్రతి ఒక్కరికీ సొంత సహాయకం అవసరం.',
    machine_translation: 'యంత్ర అనువాదం: అర్థం, సంస్కృత ఖచ్చితత్వాన్ని పరిశీలించండి.',
    experimental_conversation: 'ప్రయోగాత్మక సంభాషణ: మోడల్ భాషలను కలపవచ్చు, తప్పుడు బోధనా విషయాలు చెప్పవచ్చు. ఇది ధృవీకరించిన సంస్కృత బోధన కాదు.',
    conversationNote: 'సంభాషణకు అన్ని అనువాద మోడళ్లు, స్థానిక Qwen, సహాయకంలో స్పష్టమైన ప్రయోగాత్మక అనుమతి అవసరం.',
    transliteration_only: 'సంస్కృత ఇన్‌పుట్: సాధారణీకరణ, లిప్యంతరీకరణ మాత్రమే. అనువాదం లేదా ధృవీకరణ కాదు.',
    candidate_analysis: 'ఇవి సాధ్యమైన పద విశ్లేషణలు, వ్యాకరణ తీర్పు కాదు. విశ్లేషణ లేకపోవడం తప్పుకు రుజువు కాదు. ట్యాగ్‌లు ప్రొవైడర్ సంస్కృత పరిభాషలో ఉంటాయి.',
    provider: 'ప్రొవైడర్', ready: 'ఇన్‌స్టాల్ అయింది', missing: 'ఇన్‌స్టాల్ కాలేదు',
    unavailable: 'ఈ పనికి అవసరమైన ప్రొవైడర్ లేదు. సహాయకంలో ఇన్‌స్టాల్ చేసి స్థితిని మళ్లీ చూడండి.',
    noCandidates: 'సాధ్యమైన విశ్లేషణలు దొరకలేదు',
    speechMissing: 'స్థానిక సంస్కృత వాణి ఇంకా సక్రియం కాలేదు; హిందీ లేదా బ్రౌజర్ వాయిస్‌ను బదులుగా వాడము.',
    native: 'సహాయకం ఉన్న కంప్యూటర్‌లోని డెస్క్‌టాప్ బ్రౌజర్‌లో స్థానిక గురువును వాడండి. ఫోన్ నుంచి కంప్యూటర్ కనెక్షన్ ఇంకా లేదు.',
    unreachable: 'సహాయకం అందుబాటులో లేదు. ఈ కంప్యూటర్‌లో ప్రారంభించి స్థానిక నెట్‌వర్క్ అనుమతి ఇవ్వండి. పబ్లిక్ సైట్‌ను బ్రౌజర్ అడ్డుకుంటే localhost యాప్ తెరవండి.',
    unauthorized: 'కనెక్షన్ విఫలమైంది. ప్రస్తుత స్థానిక టోకెన్‌తో మళ్లీ కనెక్ట్ అవ్వండి.',
    forbidden_origin: 'సహాయకం ఈ పేజీ మూలాన్ని తిరస్కరించింది. అనుమతించిన localhost లేదా వాక్య Pages యాప్ వాడండి.',
    provider_unavailable: 'అవసరమైన స్థానిక ప్రొవైడర్ ఇన్‌స్టాల్ లేదా అమరిక కాలేదు.',
    busy: 'మరో స్థానిక అభ్యర్థన ఇంకా నడుస్తోంది. మళ్లీ ప్రయత్నించే ముందు వేచి ఉండండి.',
    quota_exceeded: 'ఈ రోజు అభ్యర్థనల పరిమితి పూర్తయింది. దయచేసి రేపు మళ్లీ ప్రయత్నించండి.',
    invalid_request: 'ఇన్‌పుట్ భాషను పరిశీలించి, ఖాళీ కాని చిన్న వాక్యం ఇవ్వండి.',
    invalid_output: 'ప్రొవైడర్ అసంపూర్ణ లేదా చెల్లని ఫలితం ఇచ్చింది. మళ్లీ ప్రయత్నించండి; ప్రత్యామ్నాయ సేవ వాడలేదు.',
    inference_failed: 'స్థానిక విశ్లేషణ విఫలమైంది. సహాయకం ఇన్‌స్టాలేషన్ చూసి మళ్లీ ప్రయత్నించండి.',
    clear: 'సంభాషణ క్లియర్ చేయండి',
  },
};

export const hostedCopy: typeof localCopy = {
  en: {
    ...localCopy.en,
    title: 'Sanskrit tutor',
    intro: 'Translate, converse, and explore word forms with hosted open models. No account or local installation needed. Generated Sanskrit is experimental: check important meanings with a teacher.',
    connected: 'Connected to the hosted tutor',
    connect: 'Reconnect / refresh models',
    submit: 'Send to tutor',
    working: 'The hosted model is working… Cold starts can take a few minutes.',
    connecting: 'Connecting to the hosted tutor… The service may need time to start.',
    privacy: 'Sending text shares it with the Vākya Azure model service. Listening sends Sanskrit to the speech service. Browser Sanskrit recordings stay on your device; only the edited transcript is sent when you submit. The API stores no conversations; quota counters and hashed network identifiers are retained.',
    conversationNote: 'Experimental: Qwen plans the reply; a separate translation model produces Sanskrit and your support-language explanation.',
    ready: 'Available', missing: 'Unavailable',
    unavailable: 'The selected model is unavailable. Refresh the service status or try another operation.',
    speechMissing: 'Speech uses Vāgdhenu chant synthesis, not a verified conversational Sanskrit voice.',
    unreachable: 'The hosted tutor did not respond. It may be starting or temporarily unavailable. Please reconnect.',
    unauthorized: 'The hosted service rejected the request. Please contact the service owner.',
    forbidden_origin: 'The service does not allow this website. Open the official Vākya app.',
    provider_unavailable: 'The required hosted model is not ready or configured.',
    busy: 'The service is handling another request. Please wait and retry.',
    inference_failed: 'The hosted model could not complete this request. Please retry later.',
  },
  hi: {
    ...localCopy.hi,
    title: 'संस्कृत शिक्षक',
    intro: 'होस्ट किए गए खुले मॉडलों से अनुवाद, बातचीत और शब्दरूप सीखें। खाता या स्थानीय स्थापना नहीं चाहिए। उत्पन्न संस्कृत प्रायोगिक है; महत्वपूर्ण अर्थ शिक्षक से जाँचें।',
    connected: 'ऑनलाइन शिक्षक से जुड़ा है', connect: 'फिर जुड़ें / मॉडल स्थिति देखें',
    submit: 'शिक्षक को भेजें', working: 'ऑनलाइन मॉडल काम कर रहा है… पहली बार शुरू होने में कुछ मिनट लग सकते हैं।',
    connecting: 'ऑनलाइन शिक्षक से जुड़ रहा है… सेवा शुरू होने में समय लग सकता है।',
    privacy: 'भेजने पर पाठ वाक्य की Azure मॉडल सेवा को जाता है। सुनने पर संस्कृत वाणी सेवा को जाती है। ब्राउज़र की संस्कृत रिकॉर्डिंग आपके उपकरण पर रहती है; भेजने पर केवल संपादित पाठ जाता है। API बातचीत नहीं सहेजता; सीमा गणनाएँ और हैश किए गए नेटवर्क पहचानकर्ता रखे जाते हैं।',
    conversationNote: 'प्रायोगिक: Qwen उत्तर की योजना बनाता है; अलग अनुवाद मॉडल संस्कृत और आपकी सहायक भाषा में व्याख्या देता है।',
    ready: 'उपलब्ध', missing: 'अनुपलब्ध',
    unavailable: 'चुना मॉडल उपलब्ध नहीं है। स्थिति फिर देखें या दूसरा कार्य चुनें।',
    speechMissing: 'वाणी के लिए वाग्धेनु का छंद-पाठ संश्लेषण उपयोग होता है, सत्यापित बोलचाल की संस्कृत आवाज़ नहीं।',
    unreachable: 'ऑनलाइन शिक्षक ने उत्तर नहीं दिया। सेवा शुरू हो रही होगी या अस्थायी रूप से अनुपलब्ध है। फिर जुड़ें।',
    unauthorized: 'ऑनलाइन सेवा ने अनुरोध अस्वीकार किया। सेवा संचालक से संपर्क करें।',
    forbidden_origin: 'सेवा इस वेबसाइट की अनुमति नहीं देती। आधिकारिक वाक्य ऐप खोलें।',
    provider_unavailable: 'ज़रूरी ऑनलाइन मॉडल तैयार या विन्यस्त नहीं है।',
    busy: 'सेवा दूसरा अनुरोध संभाल रही है। प्रतीक्षा करके फिर प्रयास करें।',
    inference_failed: 'ऑनलाइन मॉडल अनुरोध पूरा नहीं कर पाया। बाद में फिर प्रयास करें।',
  },
  te: {
    ...localCopy.te,
    title: 'సంస్కృత గురువు',
    intro: 'హోస్ట్ చేసిన ఓపెన్ మోడళ్లతో అనువాదం, సంభాషణ, పదరూపాలు నేర్చుకోండి. ఖాతా లేదా స్థానిక ఇన్‌స్టాలేషన్ అవసరం లేదు. రూపొందించిన సంస్కృతం ప్రయోగాత్మకం; ముఖ్యమైన అర్థాలను గురువుతో తనిఖీ చేయండి.',
    connected: 'ఆన్‌లైన్ గురువుకు కనెక్ట్ అయింది', connect: 'మళ్లీ కనెక్ట్ / మోడళ్ల స్థితి చూడండి',
    submit: 'గురువుకు పంపండి', working: 'ఆన్‌లైన్ మోడల్ పనిచేస్తోంది… మొదట ప్రారంభం కావడానికి కొన్ని నిమిషాలు పట్టవచ్చు.',
    connecting: 'ఆన్‌లైన్ గురువుకు కనెక్ట్ అవుతోంది… సేవ ప్రారంభానికి సమయం పట్టవచ్చు.',
    privacy: 'పంపిన పాఠం వాక్య Azure మోడల్ సేవకు వెళ్తుంది. వినడానికి సంస్కృతం వాణి సేవకు వెళ్తుంది. బ్రౌజర్ సంస్కృత రికార్డింగ్ మీ పరికరంలోనే ఉంటుంది; పంపినప్పుడు సవరించిన పాఠం మాత్రమే వెళ్తుంది. API సంభాషణలను నిల్వ చేయదు; పరిమితి లెక్కలు, హాష్ చేసిన నెట్‌వర్క్ గుర్తింపులు ఉంచుతుంది.',
    conversationNote: 'ప్రయోగాత్మకం: Qwen సమాధానాన్ని రూపొందిస్తుంది; వేరే అనువాద మోడల్ సంస్కృతం, మీ సహాయక భాషలో వివరణ ఇస్తుంది.',
    ready: 'అందుబాటులో ఉంది', missing: 'అందుబాటులో లేదు',
    unavailable: 'ఎంచుకున్న మోడల్ అందుబాటులో లేదు. స్థితిని మళ్లీ చూడండి లేదా మరో పని ఎంచుకోండి.',
    speechMissing: 'వాణికి వాగ్ధేను ఛందోపఠన సంశ్లేషణ వాడుతుంది; ఇది ధృవీకరించిన సంభాషణ సంస్కృత స్వరం కాదు.',
    unreachable: 'ఆన్‌లైన్ గురువు స్పందించలేదు. సేవ ప్రారంభమవుతుండవచ్చు లేదా తాత్కాలికంగా అందుబాటులో లేకపోవచ్చు. మళ్లీ కనెక్ట్ అవ్వండి.',
    unauthorized: 'ఆన్‌లైన్ సేవ అభ్యర్థనను తిరస్కరించింది. సేవ నిర్వాహకుడిని సంప్రదించండి.',
    forbidden_origin: 'సేవ ఈ వెబ్‌సైట్‌ను అనుమతించదు. అధికారిక వాక్య యాప్ తెరవండి.',
    provider_unavailable: 'అవసరమైన ఆన్‌లైన్ మోడల్ సిద్ధంగా లేదు లేదా అమరిక కాలేదు.',
    busy: 'సేవ మరో అభ్యర్థనను నిర్వహిస్తోంది. వేచి ఉండి మళ్లీ ప్రయత్నించండి.',
    inference_failed: 'ఆన్‌లైన్ మోడల్ అభ్యర్థనను పూర్తి చేయలేకపోయింది. తర్వాత మళ్లీ ప్రయత్నించండి.',
  },
};

export const tutorCopy = usingHostedTutor ? hostedCopy : localCopy;
