import { Lesson, LocalizedText, SupportLanguage } from './types';

export const languageNames: Record<SupportLanguage, string> = {
  en: 'English',
  hi: 'हिन्दी',
  te: 'తెలుగు',
};

export const lessons: Lesson[] = [
  {
    id: 'greetings',
    number: 1,
    title: { en: 'First greetings', hi: 'प्रथम अभिवादन', te: 'మొదటి పలకరింపులు' },
    subtitle: { en: 'Meet and greet with confidence', hi: 'आत्मविश्वास से अभिवादन करें', te: 'ఆత్మవిశ్వాసంతో పలకరించండి' },
    duration: 6,
    icon: 'न',
    color: '#E8733F',
    phrases: [
      {
        devanagari: 'नमस्ते',
        iast: 'namaste',
        meaning: { en: 'Hello / greetings', hi: 'नमस्कार', te: 'నమస్కారం' },
      },
      {
        devanagari: 'भवान् कथम् अस्ति?',
        iast: 'bhavān katham asti?',
        meaning: { en: 'How are you? (to a man)', hi: 'आप कैसे हैं?', te: 'మీరు ఎలా ఉన్నారు?' },
      },
      {
        devanagari: 'अहं कुशली अस्मि',
        iast: 'ahaṃ kuśalī asmi',
        meaning: { en: 'I am well', hi: 'मैं कुशल हूँ', te: 'నేను బాగున్నాను' },
      },
    ],
  },
  {
    id: 'introductions',
    number: 2,
    title: { en: 'Introduce yourself', hi: 'अपना परिचय दें', te: 'మిమ్మల్ని పరిచయం చేసుకోండి' },
    subtitle: { en: 'Say your name and ask another', hi: 'अपना और दूसरे का नाम जानें', te: 'మీ పేరు చెప్పి, ఎదుటివారి పేరు అడగండి' },
    duration: 8,
    icon: 'म',
    color: '#607D67',
    phrases: [
      {
        devanagari: 'मम नाम आर्या',
        iast: 'mama nāma āryā',
        meaning: { en: 'My name is Arya', hi: 'मेरा नाम आर्या है', te: 'నా పేరు ఆర్య' },
      },
      {
        devanagari: 'भवतः नाम किम्?',
        iast: 'bhavataḥ nāma kim?',
        meaning: { en: 'What is your name?', hi: 'आपका नाम क्या है?', te: 'మీ పేరు ఏమిటి?' },
      },
      {
        devanagari: 'भवता सह मिलित्वा आनन्दः',
        iast: 'bhavatā saha militvā ānandaḥ',
        meaning: { en: 'Pleased to meet you', hi: 'आपसे मिलकर प्रसन्नता हुई', te: 'మిమ్మల్ని కలవడం ఆనందంగా ఉంది' },
      },
    ],
  },
  {
    id: 'daily-actions',
    number: 3,
    title: { en: 'Everyday actions', hi: 'प्रतिदिन के कार्य', te: 'రోజువారీ పనులు' },
    subtitle: { en: 'Speak about what you do', hi: 'अपने कार्यों के विषय में बोलें', te: 'మీరు చేసే పనుల గురించి మాట్లాడండి' },
    duration: 10,
    icon: 'ग',
    color: '#5C6F91',
    phrases: [
      {
        devanagari: 'अहं पठामि',
        iast: 'ahaṃ paṭhāmi',
        meaning: { en: 'I read / study', hi: 'मैं पढ़ता हूँ', te: 'నేను చదువుతాను' },
      },
      {
        devanagari: 'अहं विद्यालयं गच्छामि',
        iast: 'ahaṃ vidyālayaṃ gacchāmi',
        meaning: { en: 'I go to school', hi: 'मैं विद्यालय जाता हूँ', te: 'నేను పాఠశాలకు వెళ్తాను' },
      },
      {
        devanagari: 'अहं जलं पिबामि',
        iast: 'ahaṃ jalaṃ pibāmi',
        meaning: { en: 'I drink water', hi: 'मैं पानी पीता हूँ', te: 'నేను నీరు తాగుతాను' },
      },
    ],
  },
  {
    id: 'questions',
    number: 4,
    title: { en: 'Ask simple questions', hi: 'सरल प्रश्न पूछें', te: 'సరళమైన ప్రశ్నలు అడగండి' },
    subtitle: { en: 'Who, what and where', hi: 'कौन, क्या और कहाँ', te: 'ఎవరు, ఏమిటి, ఎక్కడ' },
    duration: 9,
    icon: 'क',
    color: '#A26B48',
    phrases: [
      {
        devanagari: 'एतत् किम्?',
        iast: 'etat kim?',
        meaning: { en: 'What is this?', hi: 'यह क्या है?', te: 'ఇది ఏమిటి?' },
      },
      {
        devanagari: 'सः कुत्र अस्ति?',
        iast: 'saḥ kutra asti?',
        meaning: { en: 'Where is he?', hi: 'वह कहाँ है?', te: 'అతను ఎక్కడ ఉన్నాడు?' },
      },
      {
        devanagari: 'सा का?',
        iast: 'sā kā?',
        meaning: { en: 'Who is she?', hi: 'वह कौन है?', te: 'ఆమె ఎవరు?' },
      },
    ],
  },
];

export const ui = {
  local: { en: 'Local', hi: 'स्थानीय', te: 'స్థానికం' },
  supportLanguage: { en: 'Support language', hi: 'सहायक भाषा', te: 'సహాయక భాష' },
  welcomeTitle: { en: 'Learn Sanskrit by speaking it', hi: 'संस्कृत बोलना सीखें', te: 'సంస్కృతం మాట్లాడటం నేర్చుకోండి' },
  welcomeBody: { en: 'A personal AI tutor that listens, responds, and explains in your language.', hi: 'आपकी भाषा में समझाने वाला व्यक्तिगत AI शिक्षक।', te: 'మీ భాషలో వివరించే వ్యక్తిగత AI గురువు.' },
  languageTitle: { en: 'What language should your tutor use?', hi: 'आपका शिक्षक किस भाषा का उपयोग करे?', te: 'మీ గురువు ఏ భాషను ఉపయోగించాలి?' },
  languageBody: { en: 'Sanskrit stays at the heart of every lesson. Explanations appear in your chosen language.', hi: 'हर पाठ का केंद्र संस्कृत है। व्याख्याएँ आपकी चुनी हुई भाषा में होंगी।', te: 'ప్రతి పాఠంలో సంస్కృతమే ప్రధానంగా ఉంటుంది. వివరణలు మీరు ఎంచుకున్న భాషలో ఉంటాయి.' },
  script: { en: 'Sanskrit script', hi: 'संस्कृत लिपि', te: 'సంస్కృత లిపి' },
  scriptTitle: { en: 'How would you like to read Sanskrit?', hi: 'आप संस्कृत कैसे पढ़ना चाहेंगे?', te: 'మీరు సంస్కృతాన్ని ఎలా చదవాలనుకుంటున్నారు?' },
  scriptBody: { en: 'You can change this at any time.', hi: 'आप इसे कभी भी बदल सकते हैं।', te: 'దీన్ని ఎప్పుడైనా మార్చవచ్చు.' },
  level: { en: 'Learning level', hi: 'अध्ययन स्तर', te: 'అభ్యాస స్థాయి' },
  levelTitle: { en: 'Where should we begin?', hi: 'हम कहाँ से शुरू करें?', te: 'మనం ఎక్కడి నుంచి ప్రారంభించాలి?' },
  levelBody: { en: 'Your tutor will match its Sanskrit and explanations to you.', hi: 'आपका शिक्षक आपके स्तर के अनुसार संस्कृत और व्याख्याएँ देगा।', te: 'మీ గురువు మీ స్థాయికి తగిన సంస్కృతం, వివరణలను అందిస్తారు.' },
  back: { en: 'Back', hi: 'वापस', te: 'వెనక్కి' },
  begin: { en: 'Begin learning', hi: 'सीखना शुरू करें', te: 'నేర్చుకోవడం ప్రారంభించండి' },
  devanagari: { en: 'Devanagari', hi: 'देवनागरी', te: 'దేవనాగరి' },
  iast: { en: 'IAST transliteration', hi: 'IAST लिप्यंतरण', te: 'IAST లిప్యంతరీకరణ' },
  both: { en: 'Show both', hi: 'दोनों दिखाएँ', te: 'రెండూ చూపించండి' },
  lesson: { en: 'LESSON', hi: 'पाठ', te: 'పాఠం' },
  goodDay: { en: 'A GOOD DAY TO LEARN', hi: 'सीखने का शुभ दिन', te: 'నేర్చుకోవడానికి మంచి రోజు' },
  speakToday: { en: 'Let’s speak a little Sanskrit today.', hi: 'आज कुछ संस्कृत बोलें।', te: 'ఈ రోజు కొంత సంస్కృతం మాట్లాడుదాం.' },
  freePractice: { en: 'FREE PRACTICE', hi: 'स्वतंत्र अभ्यास', te: 'స్వేచ్ఛా సాధన' },
  chooseConversation: { en: 'Choose a conversation.', hi: 'एक वार्तालाप चुनें।', te: 'ఒక సంభాషణను ఎంచుకోండి.' },
  practiceBody: { en: 'Your AI tutor adapts each conversation to your level and gives corrections in English.', hi: 'आपका AI शिक्षक आपके स्तर के अनुसार बातचीत करता है और हिन्दी में सुधार बताता है।', te: 'మీ AI గురువు మీ స్థాయికి తగిన సంభాషణను అందించి, తెలుగులో సవరణలు చెబుతారు.' },
  start: { en: 'START', hi: 'शुरू करें', te: 'ప్రారంభించండి' },
  journey: { en: 'YOUR JOURNEY', hi: 'आपकी यात्रा', te: 'మీ ప్రయాణం' },
  progressTitle: { en: 'Small steps become fluent speech.', hi: 'छोटे कदमों से धाराप्रवाह बोलना सीखें।', te: 'చిన్న అడుగులతో అనర్గళంగా మాట్లాడటం నేర్చుకోండి.' },
  complete: { en: 'COMPLETE', hi: 'पूर्ण', te: 'పూర్తయింది' },
  lessonsFinished: { en: 'Lessons finished', hi: 'पूर्ण किए गए पाठ', te: 'పూర్తి చేసిన పాఠాలు' },
  streak: { en: 'Day streak', hi: 'लगातार अध्ययन के दिन', te: 'వరుసగా నేర్చుకున్న రోజులు' },
  phrasesMet: { en: 'Phrases you have met', hi: 'आपके सीखे हुए वाक्यांश', te: 'మీరు నేర్చుకున్న పదబంధాలు' },
  emptyProgress: { en: 'Finish your first lesson to begin your collection.', hi: 'अपना संग्रह शुरू करने के लिए पहला पाठ पूरा करें।', te: 'మీ సేకరణను ప్రారంభించడానికి మొదటి పాఠాన్ని పూర్తి చేయండి.' },
  personalise: { en: 'PERSONALISE', hi: 'अपनी पसंद चुनें', te: 'మీకు అనుగుణంగా మార్చుకోండి' },
  settingsTitle: { en: 'Make Vākya yours.', hi: 'वाक्य को अपने अनुसार बनाएँ।', te: 'వాక్యను మీకు అనుగుణంగా మార్చుకోండి.' },
  reset: { en: 'Reset app and onboarding', hi: 'ऐप और प्रारंभिक सेटिंग रीसेट करें', te: 'యాప్, ప్రారంభ అమరికలను రీసెట్ చేయండి' },
  tutorStatus: { en: 'YOUR SANSKRIT TUTOR · ONLINE', hi: 'आपका संस्कृत शिक्षक · ऑनलाइन', te: 'మీ సంస్కృత గురువు · ఆన్‌లైన్' },
  thinking: { en: 'Vākya is thinking…', hi: 'वाक्य सोच रहा है…', te: 'వాక్య ఆలోచిస్తోంది…' },
  try: { en: 'Try:', hi: 'प्रयास करें:', te: 'ప్రయత్నించండి:' },
  startRecording: { en: 'Start recording', hi: 'रिकॉर्डिंग शुरू करें', te: 'రికార్డింగ్ ప్రారంభించండి' },
  stopRecording: { en: 'Stop recording', hi: 'रिकॉर्डिंग रोकें', te: 'రికార్డింగ్ ఆపండి' },
  send: { en: 'Send', hi: 'भेजें', te: 'పంపండి' },
  close: { en: 'Close lesson', hi: 'पाठ बंद करें', te: 'పాఠం మూసివేయండి' },
  reference: { en: 'Show or hide phrases', hi: 'वाक्यांश दिखाएँ या छिपाएँ', te: 'పదబంధాలను చూపించండి లేదా దాచండి' },
  tutorError: { en: 'The tutor could not respond. Please try again.', hi: 'शिक्षक उत्तर नहीं दे सका। कृपया फिर प्रयास करें।', te: 'గురువు సమాధానం ఇవ్వలేకపోయారు. మళ్లీ ప్రయత్నించండి.' },
  tutorConfig: { en: 'The tutor API is not available on this server. Configure EXPO_PUBLIC_API_URL for AI replies. Local transcription works independently.', hi: 'इस सर्वर पर शिक्षक API उपलब्ध नहीं है। AI उत्तरों के लिए EXPO_PUBLIC_API_URL सेट करें। स्थानीय लिप्यंतरण स्वतंत्र रूप से चलता है।', te: 'ఈ సర్వర్‌లో గురువు API అందుబాటులో లేదు. AI సమాధానాల కోసం EXPO_PUBLIC_API_URL అమర్చండి. స్థానిక లిప్యంతరీకరణ విడిగా పనిచేస్తుంది.' },
  speechError: { en: 'Sanskrit speech is unavailable right now. Please try again later.', hi: 'संस्कृत वाणी अभी उपलब्ध नहीं है। कृपया बाद में पुनः प्रयास करें।', te: 'సంస్కృత వాణి ప్రస్తుతం అందుబాటులో లేదు. దయచేసి తర్వాత మళ్లీ ప్రయత్నించండి.' },
  recordingError: { en: 'The recording could not be transcribed. Please try again.', hi: 'रिकॉर्डिंग का लिप्यंतरण नहीं हो सका। कृपया फिर प्रयास करें।', te: 'రికార్డింగ్‌ను లిప్యంతరీకరించలేకపోయాం. మళ్లీ ప్రయత్నించండి.' },
  microphoneError: { en: 'Microphone permission is needed for speaking practice.', hi: 'बोलने के अभ्यास के लिए माइक्रोफ़ोन की अनुमति चाहिए।', te: 'మాట్లాడే సాధన కోసం మైక్రోఫోన్ అనుమతి అవసరం.' },
  previousReply: { en: 'Earlier reply in the previously selected language. New replies use your current language.', hi: 'यह पुराना उत्तर पहले चुनी गई भाषा में है। नए उत्तर वर्तमान भाषा में होंगे।', te: 'ఇది గతంలో ఎంచుకున్న భాషలోని పాత సమాధానం. కొత్త సమాధానాలు ప్రస్తుత భాషలో ఉంటాయి.' },
  continue: { en: 'Continue', hi: 'आगे बढ़ें', te: 'కొనసాగించండి' },
  home: { en: 'Learn', hi: 'सीखें', te: 'నేర్చుకోండి' },
  practice: { en: 'Practice', hi: 'अभ्यास', te: 'సాధన' },
  progress: { en: 'Progress', hi: 'प्रगति', te: 'పురోగతి' },
  settings: { en: 'Settings', hi: 'विन्यास', te: 'సెట్టింగ్‌లు' },
  startLesson: { en: 'Start lesson', hi: 'पाठ आरम्भ करें', te: 'పాఠం ప్రారంభించండి' },
  continueLesson: { en: 'Continue learning', hi: 'सीखना जारी रखें', te: 'నేర్చుకోవడం కొనసాగించండి' },
  yourPath: { en: 'Your learning path', hi: 'आपका अध्ययन पथ', te: 'మీ అభ్యాస మార్గం' },
  dailyGoal: { en: 'Daily goal', hi: 'दैनिक लक्ष्य', te: 'రోజువారీ లక్ష్యం' },
  minutes: { en: 'minutes', hi: 'मिनट', te: 'నిమిషాలు' },
  listen: { en: 'Listen', hi: 'सुनें', te: 'వినండి' },
  speak: { en: 'Speak', hi: 'बोलें', te: 'మాట్లాడండి' },
  explain: { en: 'Explain', hi: 'समझाएँ', te: 'వివరించండి' },
  typeReply: { en: 'Type a reply…', hi: 'उत्तर लिखें…', te: 'సమాధానం టైప్ చేయండి…' },
  finish: { en: 'Finish lesson', hi: 'पाठ पूर्ण करें', te: 'పాఠం పూర్తి చేయండి' },
  completed: { en: 'Lesson complete!', hi: 'पाठ पूर्ण हुआ!', te: 'పాఠం పూర్తయింది!' },
} satisfies Record<string, LocalizedText>;

export function t(key: keyof typeof ui, language: SupportLanguage) {
  return ui[key][language];
}
